version: '3'
services:
  influxdb:
    image: influxdb:2.1
    volumes:
      - ${DOCKER_INFLUXDB_DATA_PATH}:/var/lib/influxdb2
      - ${DOCKER_INFLUXDB_CFG_PATH}:/etc/influxdb2
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: always
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086
    networks:
      - air-Control

  telegraf:
    image: telegraf:latest
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf
    env_file:
      - .env
    links:
      - influxdb
    depends_on:
      - influxdb
    networks:
      - air-Control

  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - ${DOCKER_POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    ports:
      - ${DOCKER_POSTGRES_INIT_PORT}:5432
    networks:
      - air-Control

  backend:
    build: ./Backend
    env_file:
      - .env
    restart: always
    ports:
      - ${DOCKER_BACKEND_INIT_PORT}:8000
    depends_on:
      - postgres
    networks:
      - air-Control

  
  cors:
    image: redocly/cors-anywhere
    env_file:
      - .env
    ports:
      - ${DOCKER_CORS_BRIDGE_INIT_PORT}:8080
    networks:
      - air-Control


  frontend:
    build: ./Frontend/air_control_app
    env_file:
      - .env
    restart: always
    ports:
      - ${DOCKER_FRONTEND_INIT_PORT}:3000
    depends_on:
      - backend
    networks:
      - air-Control

networks:
  air-Control:
    driver: bridge